apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: CLUSTER_NAME
  region: REGION
  version: "K8S_VERSION"
managedNodeGroups:
  - name: NODEGROUP_NAME
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    labels: {role: worker}
    tags:
      Name: "CLUSTER_NAME-NODEGROUP_NAME"
