# k8s/serviceaccount.yaml
# This Service Account is referenced in your deployment.yaml
# If you are using IRSA for ECR image pull, you would associate an IAM Role here.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clipnetic-ai-sa
  namespace: default # Or your chosen namespace
  # If using IRSA, you'd add this annotation:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::384064000786:role/GitHubActionsECREKSRole
