# This Service Account is referenced in your deployment.yaml
# If you are using IRSA for ECR image pull, you would associate an IAM Role here.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clipnetic-ai-sa
  namespace: default # Or your chosen namespace
  # If using IRSA, you'd add this annotation:
  annotations:
    eks.amazonaws.com/role-arn: __IAM_ROLE_ARN__ # Replace with your actual IAM Role ARN for ECR access

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: clipnetic-ai-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clipnetic-ai-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: clipnetic-ai-sa
  namespace: default
roleRef:
  kind: Role
  name: clipnetic-ai-role
  apiGroup: rbac.authorization.k8s.io
